-- ============================================================================
-- Migration 010: Create drafts table with all required columns
-- ============================================================================

-- Drop existing drafts table if it exists (to start fresh)
DROP TABLE IF EXISTS drafts CASCADE;

-- Create drafts table with all required columns
CREATE TABLE drafts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject TEXT NOT NULL,
    html_content TEXT NOT NULL,
    plain_content TEXT NOT NULL,
    content_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'pending',
    metadata JSONB DEFAULT '{}'::jsonb,
    notes TEXT,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    sent_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Create indexes on drafts
CREATE INDEX idx_drafts_user_id ON drafts(user_id);
CREATE INDEX idx_drafts_status ON drafts(status);
CREATE INDEX idx_drafts_created_at ON drafts(created_at DESC);

-- Add comment to table
COMMENT ON TABLE drafts IS 'Newsletter drafts generated by AI';

-- Add comments to columns
COMMENT ON COLUMN drafts.content_data IS 'Structured newsletter content as JSON';
COMMENT ON COLUMN drafts.metadata IS 'Generation metadata (model, time, etc.)';
COMMENT ON COLUMN drafts.status IS 'Draft status: pending, reviewed, edited, sent, archived';

-- Verify all columns exist
DO $$
DECLARE
    col_count INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO col_count
    FROM information_schema.columns
    WHERE table_name = 'drafts'
    AND column_name IN (
        'id', 'user_id', 'subject', 'html_content', 'plain_content',
        'content_data', 'status', 'metadata', 'notes', 'reviewed_at',
        'sent_at', 'created_at', 'updated_at'
    );

    IF col_count = 13 THEN
        RAISE NOTICE 'SUCCESS: drafts table created with all 13 required columns';
    ELSE
        RAISE EXCEPTION 'ERROR: Expected 13 columns but found %', col_count;
    END IF;
END $$;
